### ISSUE TITLE
นัดหมายประชุม โปรเจค

### ISSUE THREAD

**Issue by slyphstia** [Mxrch200x/project-compro#1]
ประชุมวัน พุธที่15 กพ. เวลา11.00 น. นะจ๊ะ

**Comment by aeiout** [comment]
Ok

**Comment by Mxrch200x** [comment]
Yes, sir

**Comment by Goodl3oyZ** [comment]
ok krub

**Comment by Goodl3oyZ** [comment]
[งานคอมโปร.txt](https://github.com/Mxrch200x/project-compro/files/10739471/default.txt)

**Comment by Goodl3oyZ** [comment]
[The_Oxford_3000_by_CEFR_level.pdf](https://github.com/Mxrch200x/project-compro/files/10739478/The_Oxford_3000_by_CEFR_level.pdf) 
a1-b2

**Comment by Goodl3oyZ** [comment]
[pdfcoffee.com_c1-c2-vocabulary-list-pdf-free.pdf](https://github.com/Mxrch200x/project-compro/files/10739492/pdfcoffee.com_c1-c2-vocabulary-list-pdf-free.pdf)
c1-c2
