### ISSUE TITLE
คำใบ้

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#10]
ตัวอักษรใบ้เพื่อให้เล่นง่ายขึ้น

**Comment by slyphstia** [comment]
[สมุดโน้ตไม่มีชื่อ.pdf](https://github.com/Mxrch200x/project-compro/files/10873810/default.pdf)

**Comment by slyphstia** [comment]
อัพเดท คำศัพท์ที่ใช้ในเกม และคำใบ้ แต่ยังไม่สมบูรณ์

**Comment by AutsadaWiriya** [comment]
จะพิมพ์อยู่ใช่มั้ย

**Comment by slyphstia** [comment]
ใช่

**Comment by slyphstia** [comment]
[words meaning.txt](https://github.com/Mxrch200x/project-compro/files/10892257/words.meaning.txt)
เดี๋ยวอีก40คำเพิ่มให้นะ

**Comment by slyphstia** [comment]
[eng word.txt](https://github.com/Mxrch200x/project-compro/files/10894536/eng.word.txt)

**Comment by slyphstia** [comment]
[words meaning.txt](https://github.com/Mxrch200x/project-compro/files/10894602/words.meaning.txt)
ฝากลูกเกด ทำต่อด้วยนะะ

**Comment by Mxrch200x** [comment]
[new eng word1.txt](https://github.com/Mxrch200x/project-compro/files/10898034/new.eng.word1.txt)

พอดีลืมใส่ในนี้

**Comment by Mxrch200x** [comment]
[ช่วยคิดคำใบ้ภาษาอังกฤษหน่อยครับ.docx](https://github.com/Mxrch200x/project-compro/files/10917509/default.docx)

อันนี้ทำเสร็จแล้ว

**Comment by AutsadaWiriya** [comment]
ขอทำเป็น .txt แยกไฟล์ 2 อันหน่อยครับบ

**Comment by Mxrch200x** [comment]
[only eng word.txt](https://github.com/Mxrch200x/project-compro/files/10925105/only.eng.word.txt)
[hint1.txt](https://github.com/Mxrch200x/project-compro/files/10925106/hint1.txt)
[hint2.txt](https://github.com/Mxrch200x/project-compro/files/10925108/hint2.txt)

เรียบร้อยแล้วครับ ลองเช็กดูนะ

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/224090212-58f92546-9ecb-4bda-8c44-477ba288d83a.png)
