### ISSUE TITLE
นัดประชุมวันนี้ วันที่17 ก.พ. 66 หลังคาบคอมโปรนะ

### ISSUE THREAD

**Issue by ghost** [Mxrch200x/project-compro#12]
นัดประชุม วันที่17 ก.พ. 2566หลังคาบคอมโปร

**Comment by slyphstia** [comment]
ok

**Comment by Mxrch200x** [comment]
ประกาศๆ วันนี้งดประชุมเพราะLab Comproยากเกินไป  จะบอกวันนัดประชุมอีกทีขอบคุณครับ
@AutsadaWiriya @Goodl3oyZ @Hewkai @slyphstia @aeiout
