### ISSUE TITLE
ความคืบหน้า

### ISSUE THREAD

**Issue by Goodl3oyZ** [Mxrch200x/project-compro#14]

**Comment by Goodl3oyZ** [comment]
[engwords.txt](https://github.com/Mxrch200x/project-compro/files/10830522/engwords.txt)
ศัพท์ ที่จะใช้ แต่ยังไม่ได้เตรียมคำแปล คำใบ้

**Comment by Goodl3oyZ** [comment]
https://github.com/Goodl3oyZ/Code-for-Project-Hagnman-cpe
เพื่อนลืมติ๊กไฟล์ read me ลิงค์นี้จะเป็น เกี่ยวกับ code

**Comment by Goodl3oyZ** [comment]
-สามารถสุ่มคำแต่ละเลเวลมาได้ละ
-มีเลเวล เป็น 6 ระดับ
     -โดยแต่ละระดับก็สุ่มคำจาก คลังคำศัพท์ที่ไม่เหมือนกัน
       อย่างเช่น เวล1 คือ คำที่ 1-20 เวล 2 คำที่ 21-40 .....
-ขาด คำใบ้ ตัวช่วย
-ขาด คำแปล 
-ขาด การนับคะแนน เพื่อมาจัด ผู้ที่มีคะแนนสูงสุด

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/222040153-29b213dc-2f14-4051-b6ce-347519b6427c.png)

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/222040309-3d2bb9f9-5bd3-4648-a62c-619923861b45.png)

![image](https://user-images.githubusercontent.com/110963173/222040397-0f8147bf-9053-46b8-bbeb-cfc99672f1c7.png)

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/222040744-f5bbadc9-a573-432a-aa74-61800e6366f2.png)

**Comment by slyphstia** [comment]
[สมุดโน้ตไม่มีชื่อ.pdf](https://github.com/Mxrch200x/project-compro/files/10873826/default.pdf)

**Comment by slyphstia** [comment]
คำศัพท์นะ แต่ยังไม่สมบูรณ์
