### ISSUE TITLE
ออกแบบฟังก์ชั่นและ รวมฟังก์ชั่น

### ISSUE THREAD

**Issue by AutsadaWiriya** [Mxrch200x/project-compro#15]

**Comment by AutsadaWiriya** [comment]
ช่วยออกแบบฟังก์ชั่นหน่อย จะเอาฟังก์ชั่นมาประกอบรวมกันทีหลัง

**Comment by AutsadaWiriya** [comment]
ออกแบบว่าต้องทำฟังก์ชั่นอะไรบ้าง
แล้วเกมจะเรียกใช้ฟังก์ชั่นนี้ตอนไหน

**Comment by slyphstia** [comment]
ฟังก์ชั่น คำใบ้ ใช้เมื่อ ผู้เล่นขอใช้คำใบ้

**Comment by slyphstia** [comment]
ฟังก์ชั่น นับสกอ เมื่อจบเกม

**Comment by Mxrch200x** [comment]
Leader Boardที่โชว์ตอนจบเกม
Item  ที่จะช่วยผู้เล่นตอนเล่นพลาด

**Comment by AutsadaWiriya** [comment]
- [ ] sadsadasdsa
- [ ] gfdgfdgfd
