### ISSUE TITLE
ทดสอบโปรแกรม

### ISSUE THREAD

**Issue by aeiout** [Mxrch200x/project-compro#16]

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/224100398-f6186350-faae-47d9-b325-764c8ac74f9e.png)

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/224100475-1e4c2871-0afd-4ffd-81ec-2851d0a1c337.png)

**Comment by AutsadaWiriya** [comment]
โหลดเอาไปเทสให้หน่อย

**Comment by AutsadaWiriya** [comment]
กด RUN ในไฟล์ .cpp นะ

**Comment by aeiout** [comment]
![IMG_1266](https://user-images.githubusercontent.com/110966603/224331933-4552c6c4-ff7a-4557-bcae-8366b18907fd.jpg)
ระดับของคำศัพท์เป็นA2 แต่ในเกมบอกเป็นคำศัพท์ระดับB1

**Comment by aeiout** [comment]
![IMG_1265](https://user-images.githubusercontent.com/110966603/224332652-efc8d317-9305-4715-bd72-f0666fbd00ab.jpg)
ในการเล่นเกมมีการสุ่มคำศัพท์ที่ใช้เล่นมาซ้ำกันใน1ตา

**Comment by aeiout** [comment]
![IMG_1263](https://user-images.githubusercontent.com/110966603/224333067-f466782b-1b70-4fc8-8232-59eba28c1c5b.jpg)
แก้ไขhintที่1ให้ถูกต้องด้วยครับ

**Comment by aeiout** [comment]
![IMG_1262](https://user-images.githubusercontent.com/110966603/224333404-ba5b8814-e6c8-4c9a-b584-af446417ba04.jpg)
แก้ไขเป็น welcome ...... to our game
เปลี่ยนจากforเป็นto

**Comment by aeiout** [comment]
จากการทดสอบรู้สึกว่าการจะชนะเกมนั้นยากมากเนื่องจากทั้งเกมจะมีโอกาสให้แค่ 6 คร้ังและโล่ป้องกันที่ใช้ได้ 1ครั้ง กับการต้องเดาคำศัพท์ 3 คำจากทั้ง 6 ระดับ รวมถึง คำใบ้ หรือ hint ที่ดูเหมือนจะไม่ได้ช่วยอะไร(เช่น occupation/place ที่เปิดกว้างมาก)
![IMG_1264](https://user-images.githubusercontent.com/110966603/224336409-b5935f93-1ba7-4464-817d-0c997e945dc5.jpg)

**Comment by AutsadaWiriya** [comment]
> ![IMG_1266](https://user-images.githubusercontent.com/110966603/224331933-4552c6c4-ff7a-4557-bcae-8366b18907fd.jpg) ระดับของคำศัพท์เป็นA2 แต่ในเกมบอกเป็นคำศัพท์ระดับB1

ตอนนี้ได้แก้อันนี้แล้ว ตรงตาม level

**Comment by AutsadaWiriya** [comment]
> ![IMG_1265](https://user-images.githubusercontent.com/110966603/224332652-efc8d317-9305-4715-bd72-f0666fbd00ab.jpg) ในการเล่นเกมมีการสุ่มคำศัพท์ที่ใช้เล่นมาซ้ำกันใน1ตา

ได้แก้ไม่ให้มันซ้ำแล้ว

**Comment by AutsadaWiriya** [comment]
> จากการทดสอบรู้สึกว่าการจะชนะเกมนั้นยากมากเนื่องจากทั้งเกมจะมีโอกาสให้แค่ 6 คร้ังและโล่ป้องกันที่ใช้ได้ 1ครั้ง กับการต้องเดาคำศัพท์ 3 คำจากทั้ง 6 ระดับ รวมถึง คำใบ้ หรือ hint ที่ดูเหมือนจะไม่ได้ช่วยอะไร(เช่น occupation/place ที่เปิดกว้างมาก) ![IMG_1264](https://user-images.githubusercontent.com/110966603/224336409-b5935f93-1ba7-4464-817d-0c997e945dc5.jpg)

ได้แก้ไขให้มันง่ายขึ้นทั้งหมดแล้ว

**Comment by AutsadaWiriya** [comment]
ตอนนี้ได้อัพเดท โค้ดลงไปใน github แล้ว ลองเอามาเทส

ตอนนี้โค้ดยังขาดตอนจบ

**Comment by Hewkai** [comment]
![error b1](https://user-images.githubusercontent.com/110963185/225568231-0a6a45ff-c6e7-4e4d-9863-b3956cde31fa.jpg)
![error ตอนจบ](https://user-images.githubusercontent.com/110963185/225568244-3af09e13-e428-4cda-ac56-7c2774ffa83b.jpg)
![บัค c2](https://user-images.githubusercontent.com/110963185/225568250-41f84a3e-55b2-44ef-ad6f-606f7edd24c7.jpg)

รองทดสอบหลายแบบแล้วเจอบัคประมาณนี้
-บัคจบเกมแล้วไม่มีหน้าชนะ
-บัค c2 ไม่เจอคำศัพท์
-บัค B1 อ่านค่าไม่สำเร็จ

**Comment by AutsadaWiriya** [comment]
แก้บัคหมดนี่ที่บอกมาเรียบร้อย
