### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#17]
เพื่อให้เกมมีความน่าเล่นขึ้น

**Comment by slyphstia** [comment]
guiเป็นไงบ้างง

**Comment by Hewkai** [comment]
กำลังทำอยู่ๆ

**Comment by Hewkai** [comment]
ไม่ไหวพยายามทำทั้งคืนละแต่หาวิธีไม่ได้ซักที
1.รูปที่ใส่ไม่ขึ้น
2.ปุ่ม start ต้องการให้มันขึ้นหน้าใหม่เมื่อกด แต่หาวิธีไม่ได้ซักที
3.พอขยายหน้าจอแล้วส่วนอื่นไม่ขยับตามไปด้วย

Logo ไม่ขึ้น
![ปัญหา1](https://user-images.githubusercontent.com/110963185/225509435-ae1399b0-8b26-4eb3-861e-2647c78519b5.jpg)

ปุ่มไม่ขยับตาม
![ไม่ขยับตาม](https://user-images.githubusercontent.com/110963185/225509447-0312ebab-b048-4fc7-a91e-23ee85e3c561.jpg)

**Comment by Hewkai** [comment]
ใครพอจะรู้วิธีแก้ช่วยหน่อย

**Comment by Hewkai** [comment]
![4](https://user-images.githubusercontent.com/110963185/225568036-2fe2ec4a-1fcf-43a5-b23a-a059b5c5fe3f.jpg)

ได้ละเหลือปุ่ม start

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/225669109-5b1816bd-b2f9-4536-afbb-0dd7ac0be6ec.png)
ปุ่ม start

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/225671553-a9549e44-06ce-45a1-8df2-bd2104d2381b.png)
