### ISSUE TITLE
รายละเอียดเกม ที่จะทำ

### ISSUE THREAD

**Issue by slyphstia** [Mxrch200x/project-compro#2]
เป็นเกมแฮงค์แมนสำหรับ ฝึกภาษาอังกฤษ

**Comment by slyphstia** [comment]
มีระดับความยาก ในแต่ละด่านจะมีคำใบ้เพื่อไม่ให้ยากเกินในการตอบ

**Comment by AutsadaWiriya** [comment]
> เป็นเกมแฮงค์แมนสำหรับ ฝึกภาษาอังกฤษ

มีคำแปลด้วยมั้ย

**Comment by AutsadaWiriya** [comment]
https://vscode.dev/profile/github/38e0720a419887df8f3c44d043111df3

**Comment by Goodl3oyZ** [comment]
รายละเอียดเกม หลังประชุมรอบที่ 1
c1-c2:[pdfcoffee.com_c1-c2-vocabulary-list-pdf-free.pdf](https://github.com/Mxrch200x/project-compro/files/10739504/pdfcoffee.com_c1-c2-vocabulary-list-pdf-free.pdf)
[งานคอมโปร.txt](https://github.com/Mxrch200x/project-compro/files/10739507/default.txt)
a1-c2 :[The_Oxford_3000_by_CEFR_level.pdf](https://github.com/Mxrch200x/project-compro/files/10739508/The_Oxford_3000_by_CEFR_level.pdf)

**Comment by Mxrch200x** [comment]
[The_Oxford_5000_by_CEFR_level.pdf](https://github.com/Mxrch200x/project-compro/files/10885607/The_Oxford_5000_by_CEFR_level.pdf)
ไฟล์คำ c1 oxford
