### ISSUE TITLE
จะทำprojectเกี่ยวกับอะไรดี

### ISSUE THREAD

**Issue by Mxrch200x** [Mxrch200x/project-compro#3]
- เกม
- เครื่องมือทาวคณิตศาสตร์
- โปรแกรมวิเคราะห์ข้อมูล
- ระบบเกี่ยวกับการเรียนการสอน
- ระบบจัดการกิจการต่างๆ
- โปรแกรมใช้งานอื่นๆ

**Comment by Mxrch200x** [comment]
เราโหวตเกม

**Comment by AutsadaWiriya** [comment]
โหวตเกมด้วยคน

**Comment by slyphstia** [comment]
เกมจ้า
