### ISSUE TITLE
ออกแบบตัว Hangman

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#4]
Hangman แต่ละคนวาดไม่เหมือนกัน จึงต้องรวบรวมการวาดในแบบต่างๆเพื่อหาอันที่เหมาะสมที่สุด

**Comment by Hewkai** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/110963185/218939885-9e174690-e3d3-4e8f-bf6c-55bf84f95c6f.png)

**Comment by AutsadaWiriya** [comment]
1

**Comment by Goodl3oyZ** [comment]
2

**Comment by Mxrch200x** [comment]
เราเอา 1 + 3

**Comment by AutsadaWiriya** [comment]
> เราเอา 1 + 3

++++
