### ISSUE TITLE
ทำเกมอะไรดี?

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#5]
หลังจากที่โหวดหัวข้อกัน สรุปคือจะทำเกม จึงต้องมาเสนอต่อว่าจะทำเกมแนวอะไร

**Comment by Hewkai** [comment]
1.Tetris
![Screenshot_1](https://user-images.githubusercontent.com/110963185/218940359-aecd5854-6185-4e0b-8e53-dc3a986e1933.png)

**Comment by Hewkai** [comment]
2.Hangman
![Screenshot_2](https://user-images.githubusercontent.com/110963185/218940442-384cf1cc-61c8-41d7-b2f3-54f8d7758377.png)

**Comment by Hewkai** [comment]
3. Text Adventure
![Screenshot_1](https://user-images.githubusercontent.com/110963185/218940514-d7e6761e-c7a1-4167-a331-830faa2f7429.png)

**Comment by Goodl3oyZ** [comment]
2 +++++

**Comment by slyphstia** [comment]
2+++

**Comment by Mxrch200x** [comment]
เราก็เลือก2 จากที่คุยกันในดิสคอร์ดสรุปได้ว่าจะทำHangman นะ
