### ISSUE TITLE
ออกแบบ Level

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#6]
มีกี่ด่าน และแต่ละด่านมีกี่เลเวล

**Comment by Goodl3oyZ** [comment]
a1 a2 b1 b2 c1c2 รวม  6 เลเวล โดยเราจะเลือกคำศัพท์จากระดับต่างๆมาเก็บในไฟล์เพื่อสุ่มอย่างละ 20 คำ รวมทั้งหมด 120 คำ ซี่งแต่ละเลเวลของเกมจะสุ่มมาให้ตอบให้ถูก เพียง 3 คำ เพื่อผ่านไปในระดับถัดไป (เสนอเพิ่มเติมได้) ยังไม่แน่นอน
