### ISSUE TITLE
ระดับความยาก

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#7]
ต้องทำระดับความยากเพื่อนให้สนุกและเพอ่มความท้าทาย

**Comment by Goodl3oyZ** [comment]
เพิ่มเติม ระดับความยากจะเป็นตามเลเวลของคำศัพท์ที่บัญญัติ โดย มหาวิทยาลัย oxford ที่ตั้งแต่ระดับ a1-c2 โดยแต่ละเวล จะมีถึง 3 คำ(ยังไม่แน่นอน) และแต่ละครั้งที่จะเพิ่มเลเวลจะมีการrandom โอกาสในการได้รับitem ช่วย ถ้าตอบผิดที่เลเวลไหนก็จะ announce มาประมาณว่า ระดับคำศัพท์ภาษาอังกฤษของคุณอยู่ในเลเวลนั้นๆ
