### ISSUE TITLE
Item ช่วย?

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#8]
เพื่อทำให้เกมต่างจากHangman ปกติ ควรเพิ่มไอเทมอะไรดี?

**Comment by Hewkai** [comment]
-คำใบ้
-โล่ป้องกัน

**Comment by Goodl3oyZ** [comment]
เพิ่มเติม คำใบ้ จะเป็นประเภท ใบ้ตัวอักษรตัวหน้าหรือ ตัวหน้า ไม่ก็ใบ้ตัวสะกด(aeiou) หรืออาจจะเป็นใบ้ด้วยคำแปล
ส่วนโล่ป้องกัน จะทำให้ การเติมตัวอักษรที่ผิดนั้นไม่ถูกนับว่าต้องขีดเส้นเจ้าตัว hangmanเพิ่ม (เสนอเพิ่มเติมได้) #อาจจะมีการตัดออกหรือเพิ่มบางอย่างภายหลัง
