### ISSUE TITLE
โล่ป้องกัน

### ISSUE THREAD

**Issue by Hewkai** [Mxrch200x/project-compro#9]
เมื่อตอบผิดจะไม่มีการเขียนเส้นเพิ่ม

**Comment by Mxrch200x** [comment]
แล้วอันนี้คือเราต้องให้ผู้เล่นกดใช้เองหรือจะใช้ให้อัตโนมัติ

**Comment by AutsadaWiriya** [comment]
ใช้ดีกว่าา

**Comment by AutsadaWiriya** [comment]
โล่นี่จะได้ตอนไหน

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/224556308-bd86da2f-de77-4011-a124-354ba7669fd3.png)
level 0 คือ ศัพท์แรก มีทั้งหมด 18คำศัพท์
จะมีโล่ป้องกันให้ตามนี้ แก้ไขได้เพิ่มหรือลดได้ แสดงความคิดเห็นกันเลย

**Comment by slyphstia** [comment]
โอเคแล้วนะ

**Comment by slyphstia** [comment]
![image](https://user-images.githubusercontent.com/110963884/225662615-c92b42da-b5b5-47d0-8663-286061a3f66c.png)
มีการปรับprotectให้ลดลงเพราะเนื่องจากง่ายเกิน
